//  CategoryViewModel.swift
//  Base
//
//  Created by BaoHoang on 31/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import RxSwift
import RxCocoa

class CategoryViewModel: BaseViewModel {
    
    struct Input {
        
    }
    
    struct Output {
    }
    
    private let bag = DisposeBag()

    func transform(input: Input) -> Output {
        return Output()
    }
}
