//  CategoryViewModel.swift
//  Base
//
//  Created by BaoHoang on 31/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import RxSwift
import RxCocoa
import SwiftSoup

class CategoryViewModel: BaseViewModel {
    
    struct Input {
        let getAllComic: Driver<Void>
    }
    
    struct Output {
    }
    
    private let bag = DisposeBag()
    private let categoryUC: CategoryUC
    
    init(categoryUC: CategoryUC) {
        self.categoryUC = categoryUC
    }

    func transform(input: Input) -> Output {
        
        let allComicOutput = input.getAllComic
            .asObservable()
            .flatMapLatest { _ in
                return self.categoryUC.getAll(param: [:])
            }
        
        return Output()
    }
}
