//  CategoryCoordinator.swift
//  Base
//
//  Created by BaoHoang on 31/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import UIKit

// khai báo các phương thức điều hướng
protocol CategoryRoutes: AnyObject {
    func navigateToComicDetail(comicDetailUrl: String, title: String)
}

class CategoryCoordinator {
   
    private var navigator: UINavigationController

    init(navigator: UINavigationController) {
        self.navigator = navigator
    }
    
}

// logic các phương thức điều hướng
extension CategoryCoordinator: CategoryRoutes {
    func navigateToComicDetail(comicDetailUrl: String, title: String) {
        let comicDetailVC = ComicDetailViewController()
        let comicDetailVM = ComicDetailViewModel(detailComicUrl: comicDetailUrl,
                                                 comicDetailUC: ComicDetailUC(repository: ComicDetailRepository()),
                                                 coordinator: ComicDetailCoordinator(navigator: navigator))
        comicDetailVC.bind(to: comicDetailVM)
        comicDetailVC.hidesBottomBarWhenPushed = true
        comicDetailVC.title = title
        navigator.pushViewController(comicDetailVC, animated: true)
    }
}
