//  CategoryViewController.swift
//  Base
//
//  Created by BaoHoang on 31/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import RxSwift
import RxCocoa

class CategoryViewController: BaseViewController<CategoryViewModel> {
    
    private let bag = DisposeBag()
    
    weak var categoryRoute: CategoryRoutes?
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    deinit {
        print("CategoryViewController deinit ✅")
    }
    
    private func setupUI() {
        
    }
    
    override func bindViewModel() {
        let input = CategoryViewModel.Input(getAllComic: Driver.just(()))
        let output = viewModel.transform(input: input)
    }
}
