//  FavoriteViewModel.swift
//  Base
//
//  Created by BaoHoang on 09/02/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import RxSwift
import RxCocoa

class FavoriteViewModel: BaseViewModel {
    
    struct Input {
        let getAllFavorite: Driver<Void>
        let didSelectItem: Driver<ComicSuggestModel>
    }
    
    struct Output {
        let favoriteComic: Driver<[ComicSuggestModel]>
        let comicSuggestIsEmpty: Driver<Bool>
    }
    
    private let bag = DisposeBag()
    private let favoriteUC: FavoriteUC
    private let coordinator: FavoriteCoordinator
    let getAllFavoriteSubject = PublishSubject<Void>()
    
    init(favoriteUC: FavoriteUC, coordinator: FavoriteCoordinator) {
        self.favoriteUC = favoriteUC
        self.coordinator = coordinator
    }

    func transform(input: Input) -> Output {
        let favoriteMerge = Driver.merge(input.getAllFavorite, getAllFavoriteSubject.asDriver(onErrorJustReturn: ()))
        let comicSuggestSubjectIsEmpty = BehaviorSubject<Bool>(value: true)
        
        let favoriteComicOutput = favoriteMerge
            .flatMap({ _ in
                return self.favoriteUC.getAllFavorite()
                    .asDriver(onErrorJustReturn: [])
            })
            .do(onNext: { data in
                comicSuggestSubjectIsEmpty.onNext(!data.isEmpty)
            })
        
        input.didSelectItem
            .asObservable()
            .subscribe(onNext: { data in
                self.coordinator.navigateToComicDetail(comicDetailUrl: data.detailUrl ?? "", title: data.title ?? "")
            })
            .disposed(by: bag)
                
        let comicSuggestIsEmptyOutput = comicSuggestSubjectIsEmpty.asDriver(onErrorJustReturn: true)
                
        return Output(favoriteComic: favoriteComicOutput,
                      comicSuggestIsEmpty: comicSuggestIsEmptyOutput)
    }
}
