//  FavoriteViewController.swift
//  Base
//
//  Created by BaoHoang on 09/02/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import RxSwift
import RxCocoa

class FavoriteViewController: BaseViewController<FavoriteViewModel> {
    
    @IBOutlet weak var tableView: UITableView!
    @IBOutlet weak var tabbarHeaderBaseView: TabbarHeaderBaseView!
    @IBOutlet weak var stackEmptyView: UIStackView!
    @IBOutlet weak var emptyContentLabel: UILabel!
    @IBOutlet weak var emptyTitleLabel: UILabel!
    
    private let bag = DisposeBag()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
        setupNotificationCenter()
    }
    
    deinit {
        print("FavoriteViewController deinit ✅")
    }
    
    private func setupNotificationCenter() {
        NotificationCenter.default.addObserver(self,
                                               selector: #selector(updateFavorite),
                                               name: NSNotification.Name(NotificationCenterKey.favorite),
                                               object: nil)
    }
    
    private func setupUI() {
        tabbarHeaderBaseView.configView(title: L10n.Common.Tab.favorite)
        tableView.sectionFooterHeight = 0.01
        tableView.sectionHeaderHeight = 0.01
        tableView.separatorStyle = .none
        tableView.showsVerticalScrollIndicator = false
        tableView.delegate = self
        tableView.registerCell(type: ComicSuggestTableViewCell.self)
        emptyTitleLabel.text = L10n.Favorite.Empty.title
        emptyContentLabel.text = L10n.Favorite.Empty.content
        emptyTitleLabel.font = UIFont.systemFont(ofSize: 18, weight: .bold)
        emptyContentLabel.font = UIFont.systemFont(ofSize: 14, weight: .regular)
    }
    
    @objc private func updateFavorite() {
        viewModel.getAllFavoriteSubject.onNext(())
    }
    
    override func bindViewModel() {
        let input = FavoriteViewModel.Input(getAllFavorite: Driver.just(()),
                                            didSelectItem: tableView.rx.modelSelected(ComicSuggestModel.self).asDriver())
        let output = viewModel.transform(input: input)
        
        output.favoriteComic
            .drive(tableView.rx.items) { tableView, index, data in
                let cell = tableView.dequeueReusableCell(type: ComicSuggestTableViewCell.self, forIndexPath: IndexPath.init(row: index, section: 0))
                cell.configCell(data: data)
                return cell
            }
            .disposed(by: bag)
        
        output.comicSuggestIsEmpty
            .drive(stackEmptyView.rx.isHidden)
            .disposed(by: bag)
    }
}

extension FavoriteViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 130
    }
}
