//  SearchCoordinator.swift
//  Base
//
//  Created by BaoHoang on 27/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import UIKit

// khai báo các phương thức điều hướng
protocol SearchRoutes: AnyObject {
    func navigateToComicDetail(comicDetailUrl: String, title: String)
}

class SearchCoordinator: Coordinator {
   
    private var navigator: UINavigationController
    private var ComicCoordinator: ComicDetailCoordinator?

    init(navigator: UINavigationController) {
        self.navigator = navigator
    }
    
    // khởi tạo màn và điều hướng
    func start() {
        let searchVC = SearchViewController()
        searchVC.routesDelegate = self // gán delegate cho view contoller quản lý route nếu có
        searchVC.bind(to: SearchViewModel(searchUC: SearchUC(repository: SearchRepository())))
        navigator.pushViewController(searchVC, animated: true)
    }
}

// logic các phương thức điều hướng
extension SearchCoordinator: SearchRoutes {
    // chuyển coordinator thì làm như dưới, điều hướng các màn thuộc coordinator thì push bình thường
    func navigateToComicDetail(comicDetailUrl: String, title: String) {
        let comicDetailCoordinator = ComicDetailCoordinator(navigator: navigator,
                                                            comicDetailUrl: comicDetailUrl,
                                                            title: title)
        comicDetailCoordinator.start()
        self.ComicCoordinator = comicDetailCoordinator
    }
}
