//  HomeCoordinator.swift
//  Base
//
//  Created by BaoHoang on 15/10/2022.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import UIKit

// khai báo các phương thức điều hướng
protocol HomeRoutes: AnyObject {
    func navigateToComicDetail(comicDetailUrl: String, title: String)
}

class HomeCoordinator: Coordinator {
   
    private var navigator: UINavigationController
    private var comicCoordinator: ComicDetailCoordinator?
    
    init(navigator: UINavigationController) {
        self.navigator = navigator
    }
    
    // khởi tạo màn và điều hướng
    func start() {
        let homeVC = HomeViewController()
        let homeVM = HomeViewModel()// gán delegate cho view contoller quản lý route nếu có
        homeVC.bind(to: homeVM)
        navigator.pushViewController(homeVC, animated: true)
        homeVC.routesDelegate = self
    }
}

// logic các phương thức điều hướng
extension HomeCoordinator: HomeRoutes {
    // chuyển coordinator thì làm như dưới, điều hướng các màn thuộc coordinator thì push bình thường
    func navigateToComicDetail(comicDetailUrl: String, title: String) {
        let comicDetailCoordinator = ComicDetailCoordinator(navigator: navigator,
                                                            comicDetailUrl: comicDetailUrl,
                                                            title: title)
        comicDetailCoordinator.start()
        self.comicCoordinator = comicDetailCoordinator
    }
    
}
