//  ComicDetailViewController.swift
//  Base
//
//  Created by baohoang on 20/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import RxSwift
import RxCocoa

class ComicDetailViewController: BaseViewController<ComicDetailViewModel> {
    
    private let bag = DisposeBag()
    weak var routesDelegate: ComicDetailRoutes?
    @IBOutlet weak var button: UIButton!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupUI()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.setNavigationBarHidden(false, animated: animated)
    }

    deinit {
        print("ComicDetailViewController deinit ✅")
    }
    
    private func setupUI() {
        
    }
    
    @IBAction func toChapterDetail(_ sender: Any) {
        routesDelegate?.navigateToChapterDetail()
    }
    
    override func bindViewModel() {
        let input = ComicDetailViewModel.Input()
        let output = viewModel.transform(input: input)
    }
}
