//  ComicDetailCoordinator.swift
//  Base
//
//  Created by baohoang on 20/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import Foundation
import UIKit

// khai báo các phương thức điều hướng
protocol ComicDetailRoutes: AnyObject {
    func navigateToChapterDetail(chapter: ChapterModel, listChapter: [ChapterModel], comicName: String)
    func goBack()
}

class ComicDetailCoordinator {
    
    private var navigator: UINavigationController

    init(navigator: UINavigationController) {
        self.navigator = navigator
    }
    
}

// logic các phương thức điều hướng
extension ComicDetailCoordinator: ComicDetailRoutes {
    // chuyển coordinator thì làm như dưới, điều hướng các màn thuộc coordinator thì push bình thường
    func navigateToChapterDetail(chapter: ChapterModel, listChapter: [ChapterModel], comicName: String) {
        let chapterDetailVC = ChapterDetailViewController()
        let chapterDetailVM = ChapterDetailViewModel(chapter: chapter,
                                                     chapterDetailUC: ChapterDetailUC(repository: ChapterDetailRepository()),
                                                     coordinator: self,
                                                     listChapter: listChapter.reversed(),
                                                     comicName: comicName)
        chapterDetailVC.bind(to: chapterDetailVM)
        chapterDetailVC.hidesBottomBarWhenPushed = true
        chapterDetailVC.title = chapter.title ?? ""
        navigator.pushViewController(chapterDetailVC, animated: true)
    }
    
    func goBack() {
        navigator.popViewController(animated: true)
    }
    
}
