//  ChapterDetailAPIRouter.swift
//  Base
//
//  Created by baohoang on 23/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum ChapterDetailRouter {
    case getChapter(url: String)
    case getChapterImg(url: String)
}

extension ChapterDetailRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        switch self {
        case .getChapterImg:
            let headers: HTTPHeaders = ["Referer":"https://www.nettruyenking.com"]
            return headers
        default:
            return nil
        }
    }
    
    var url: String {
        switch self {
        case .getChapter(let url):
            return url
        case .getChapterImg(url: let url):
            return url
        }
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .getChapter:
            return .get
        case .getChapterImg:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .getChapter:
            return [:]
        case .getChapterImg:
            return [:]
        }
    }
}
