//  ComicDetailRouterAPIRouter.swift
//  Base
//
//  Created by baohoang on 21/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum ComicDetailRouter {
    case detail(urlStrPath: String)
}

extension ComicDetailRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        return nil
    }
    
    var url: String {
        switch self {
        case .detail(let URL):
            return URL
        }
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .detail:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .detail:
            return [:]
        }
    }
}
