//  HomeAPIRouter.swift
//  Base
//
//  Created by BaoHoang on 15/10/2022.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum GeoLocationRouter {
    case geocoding(param: [String : Any]?)
}

extension GeoLocationRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        return nil
    }
    
    var url: String {
        switch self {
        case .geocoding:
            return "\(DomainUrl().domain)\(GeoCodingURL.getCoordinate)"
        }
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .geocoding:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .geocoding(var param):
            param?.updateValue(BaseApiRequest.apiKey, forKey: "appid")
            return param
        }
    }
}
