//  SearchAPIRouter.swift
//  Base
//
//  Created by BaoHoang on 27/01/2023.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum SearchRouter {
    case search(keyword: String)
}

extension SearchRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        return nil
    }
    
    var url: String {
        return "\(BaseApiRequest.url)\(nettruyenPath.search)"
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .search:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .search(let key):
            return ["q": key]
        }
    }
}
