//  HomeAPIRouter.swift
//  Base
//
//  Created by BaoHoang on 15/10/2022.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum TopComicRouter {
    case hot(param: [String : Any]?)
    case top(param: [String: Any]?)
    case topManhwa(param: [String: Any]?)
    case topManhua(param: [String: Any]?)
    case nominate
}

extension TopComicRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        return nil
    }
    
    var url: String {
        switch self {
        case .hot:
            return "\(DomainUrl().domain)\(nettruyenPath.hotPath)"
        case .top:
            return "\(DomainUrl().domain)\(nettruyenPath.manga)"
        case .nominate:
            return "\(DomainUrl().domain)"
        case .topManhwa:
            return "\(DomainUrl().domain)\(nettruyenPath.manhwa)"
        case .topManhua:
            return "\(DomainUrl().domain)\(nettruyenPath.manhua)"
        }
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .hot:
            return .get
        case .top:
            return .get
        case .nominate:
            return .get
        case .topManhwa:
            return .get
        case .topManhua:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .hot(let param):
            return param
        case .top(let param):
            return param
        case .nominate:
            return [:]
        case .topManhwa(param: let param):
            return param
        case .topManhua(param: let param):
            return param
        }
    }
}
