//  HomeAPIRouter.swift
//  Base
//
//  Created by BaoHoang on 15/10/2022.
//  Copyright (c) baohg. All rights reserved.
//
//  This file was generated by the Educa MVVM-C Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  Template created by baohg - bao15899@gmail.com

import UIKit
import Alamofire

enum TopComicRouter {
    case hot(param: [String : Any]?)
    case top(param: [String: Any]?)
    case nominate
    case getChaper
}

extension TopComicRouter: APIInputBase {
    
    var headers: Alamofire.HTTPHeaders? {
        switch self {
        case .getChaper:
            let headers: HTTPHeaders = ["Referer":"https://www.nettruyenking.com"]
            print(headers)
            return headers
        default:
            return nil
        }
    }
    
    var url: String {
        switch self {
        case .hot:
            return "\(BaseApiRequest.url)\(nettruyenPath.hotPath)"
        case .top:
            return "\(BaseApiRequest.url)\(nettruyenPath.hotPath)"
        case .nominate:
            return "\(BaseApiRequest.url)"
        case .getChaper:
            return "https://p.ntcdntempv26.com/content/image.jpg?data=Iq3+174PFlzsdGolQ82GVrlEpb/Sd7Xo00CGOy0uu4FClwcJOnnSoWbAJeAPgWFhFOomKlcq61BjSXvOAB6pMA==" // gán url ảnh
        }
    }
    
    var method: Alamofire.HTTPMethod {
        switch self {
        case .hot:
            return .get
        case .top:
            return .get
        case .nominate:
            return .get
        case .getChaper:
            return .get
        }
    }
    
    var encoding: Alamofire.ParameterEncoding {
        return method == .get ? URLEncoding.default : JSONEncoding.default
    }
    
    
    var parameters: [String : Any]? {
        switch self {
        case .hot(let param):
            return param
        case .top(let param):
            return param
        case .nominate:
            return [:]
        case .getChaper:
            return [:]
        }
    }
}
